### ISSUE TITLE
Error: Unbound module Lwt_log_core

### ISSUE THREAD

**Issue by Freyr666** [vbmithr/ocaml-websocket#104]
websocket-lwt 2.11 fails to install alongside with lwt 4.2. It seems due to removal of the logging facilities.

Edit: It seems that it's fixed already in master, so just looking for a next release.

**Comment by vbmithr** [comment]
On 9/24/18 8:08 PM, Freyr666 wrote:
> websocket-lwt 2.11 fails to install alongside with lwt 4.2. It seems due
> to removal of the logging facilities.
> 

Thanks, yeah, let me release a new version asap.
