### ISSUE TITLE
Release 2.13 on opam

### ISSUE THREAD

**Issue by copy** [vbmithr/ocaml-websocket#109]
The latest version on master (2.12) is [constrained to base64<3.0.0](https://github.com/ocaml/opam-repository/pull/13297). It looks like this is already fixed in 2.13 on master.

**Comment by vbmithr** [comment]
Ok will release a new version.

**Comment by vbmithr** [comment]
https://github.com/ocaml/opam-repository/pull/13681

**Comment by copy** [comment]
Merci!
