### ISSUE TITLE
Update to Conduit 3.0.0

### ISSUE THREAD

**Issue by MisterDA** [vbmithr/ocaml-websocket#120]
Hi!
Conduit 3.0.0 was released on Oct 20, 2020. Are there plans to update to the new version?
Thanks!

**Comment by vbmithr** [comment]
See https://github.com/vbmithr/ocaml-websocket/pull/118

I accept patches to move to `mimic`, since people tell me it's the new way to go now.

**Comment by mseri** [comment]
`mimic` is still experimental, it may even become `conduit X` once the API becomes stable and consensus is reached. The new conduit 4.0.0 is backward compatible, no action needed
