### ISSUE TITLE
Closing client connections

### ISSUE THREAD

**Issue by paurkedal** [vbmithr/ocaml-websocket#125]
`Websocket_lwt_unix.with_connection` does not provide a way of closing the socket after the session terminates.  I'm using 2.14 but checked also the current definition in the master branch.  Assuming you agree, what would be the best way of fixing it?

  - Changing the returned pair of functions into a triple, the last being a close function, would be in line with the current design, but would break backwards compatibility.
  - Automatically closing when encountering a close frame to keep the current interface? In this case, if the server closes, should the connection be closed, or should the client respond with a close?
  - Adding an abstract type for the connection with corresponding send, receive, and close functions.

**Comment by vbmithr** [comment]
Closed via https://github.com/vbmithr/ocaml-websocket/commit/1788438561521c71f8a2cfb93d8c7264f06ef6ec. Please reopen if there is still an issue here.
