### ISSUE TITLE
Missing lwt_io_ext.cmi

### ISSUE THREAD

**Issue by zoggy** [vbmithr/ocaml-websocket#23]
Hello,

I just opam-upgraded to websocket 0.9.1 and lwt_io_ext.cmi is not installed. All i have is:
````
META         websocket.a    websocket.cmi   websocket.cmx   websocket.cmxs
opam.config  websocket.cma  websocket.cmti  websocket.cmxa  websocket.mli
````

**Comment by vbmithr** [comment]
Hi,

Do you really need this file ? It is supposed to be an internal library, not accessible to the user. Do you think I should export lwt_io_ext as a library for the user ?

**Comment by zoggy** [comment]
Ok. I was using ``Lwt_io_ext.sockaddr_of_dns`` but I guess I can live without it.

**Comment by vbmithr** [comment]
This should be in Lwt ! :) Well, now that I have commit access to Lwt, I could change something about it :))
