### ISSUE TITLE
Optional TLS Support

### ISSUE THREAD

**Issue by j0sh** [vbmithr/ocaml-websocket#27]
Would be nice if the TLS support was optional, because forcing TLS introduces a lot of other dependencies, including on external C shared libs (libgmp), which affects other parts of the stack in undesirable ways (conduit/cohttp). 

Per-project OPAM switches on my side would mitigate this issue, but since TLS isn't required for websockets, it'd be nice to use this library without dragging in all a bunch of extra stuff. Might make the API cleaner as well.

For example, downloading ocaml-websockets causes conduit/cohttp to be re-compiled with the extra TLS dependencies, which "infects" all other cohttp projects with those extra dependencies, even if TLS is not being used. This is especially problematic for binary portability if any external shared libraries are not typically installed by default in a base system -- libgmp is not.

**Comment by vbmithr** [comment]
On 25/04/2015 00:01, Josh Allmann wrote:
> Would be nice if the TLS support was optional,

Ok, I'll do this :)

**Comment by vbmithr** [comment]
Switched to the awesome library http://github.com/mirage/ocaml-conduit, removing any direct dependency to TLS.
