### ISSUE TITLE
How to detect closed connection

### ISSUE THREAD

**Issue by reynir** [vbmithr/ocaml-websocket#30]
It seems to me there's no way to detect when a connection is closed. On this [line](https://github.com/vbmithr/ocaml-websocket/blob/master/lib/websocket.ml#L199) the exception Close_frame_received is raised, but the exception is not exported in the .mli. In my testing it seems the exception sometimes is raised twice, and my guess is when 1) the close frame is received, 2) when the underlying socket is closed.

**Comment by j0sh** [comment]
Here is a workaround until a proper fix is in place: https://github.com/vbmithr/ocaml-websocket/pull/28

Note that LWT_LOG needs to be set. (Why, I don't know...)

**Comment by vbmithr** [comment]
Strange. I'd like to rewrite all this to make it less dependent on Lwt anyway. I'm a bit scared by all those "strange" bugs to be honest. I'm gonna have a serious look at it soon, sorry for the delay.

**Comment by vbmithr** [comment]
Fixed in HEAD.
