### ISSUE TITLE
missing websocket.cmi

### ISSUE THREAD

**Issue by zoggy** [vbmithr/ocaml-websocket#34]
Hello,

It seems like websocket.cmi is not installed (current HEAD). I don't understand anything in the build system. I modified websocket.install but it was overwritten by the setup.exe -configure :-/

**Comment by vbmithr** [comment]
On 18/06/2015 15:44, Zoggy wrote:
> but it was overwritten by the setup.exe -configure :-/

setup.exe -configure ?!

websocket does not use oasis anymore, I don't understand your error
right now. I'm having a look about the cmi.

-- 
Vincent

**Comment by vbmithr** [comment]
On 18/06/2015 15:44, Zoggy wrote:
> Hello,
> 
> It seems like websocket.cmi is not installed (current HEAD). I don't
> understand anything in the build system. I modified websocket.install
> but it was overwritten by the setup.exe -configure :-/
> 

Yes, you need to use Websocket_lwt now. Websocket is a hidden library
that you are not supposed to use directly (hence the absence of .cmi).

Hope that helps!

-- 
Vincent

**Comment by zoggy** [comment]
Ah, setup.exe was an old file standing there :)
Ok, I'll use Websocket_lwt. Thanks again !
