### ISSUE TITLE
Adding functions to the library

### ISSUE THREAD

**Issue by zoggy** [vbmithr/ocaml-websocket#35]
I'd like to add convenient functions in Websocket_lwt. For example:
- `establish_standard_server` which would create a server and already handle some frame like in the `server` function of the `wscat.ml` example,
- `mk_frame_stream : (unit -> Frame.t Lwt.t) -> Frame.t Lwt_stream.t` which would terminate the stream when a close frame is received.

What do you think about that ? I could create a separate library of course, but I think these functions would have their place in Websocket.

**Comment by vbmithr** [comment]
On 18/06/2015 16:30, Zoggy wrote:
> I'd like to add convenient functions in Websocket_lwt. For example:
> 
>   * |establish_standard_server| which would create a server and already
>     handle some frame like in the |server| function of the |wscat.ml|
>     example,
>   * |mk_frame_stream : (unit -> Frame.t Lwt.t) -> Frame.t Lwt_stream.t|
>     which would terminate the stream when a close frame is received.
> 
> What do you think about that ? I could create a separate library of
> course, but I think these functions would have their place in Websocket.
> 

Ok, good idea! Those functions definitely have their place in Websocket,
I just decided to remove as much as possible high level features from
the basic functions, but higher level and separate convenience functions
are a good idea.

Just do a PR when you're happy with the result.

-- 
Vincent

**Comment by vbmithr** [comment]
Merged, thanks!
