### ISSUE TITLE
Error with 'opam install websocket' (v2.1)

### ISSUE THREAD

**Issue by Fourchaux** [vbmithr/ocaml-websocket#41]
Hello,
with  $ opam install websocket 

I have :
=== ERROR while installing websocket.2.1 =====================================#
opam-version 1.2.2
os           linux
compiler     4.02.3
[...]

File "lib/websocket_lwt.ml", line 30, characters 6-22:
Error: Unbound value CU.Request.write
Command exited with code 2.

The following actions failed
  ∗  install websocket 2.1
No changes have been performed

This error occurs after the last cohttp update (from v0.18.3 to 0.19.0)

**Comment by vbmithr** [comment]
Yeah, v2.1 is not compatible with cohttp >= 0.19.0, it has been fixed in opam.
I'm releasing a new version compatible with latest cohttp (hopefully with Async support as well).
