### ISSUE TITLE
OPAM package does not install websocket.cmi

### ISSUE THREAD

**Issue by darioteixeira** [vbmithr/ocaml-websocket#42]
(Websocket version 2.1)

**Comment by darioteixeira** [comment]
Btw, the `cmt` file is also missing.

**Comment by vbmithr** [comment]
Yeah, this is normal, it is because Websocket is an internal module, you should only interact with Websocket_lwt.

Is there any reason why you'd want those files ?

**Comment by darioteixeira** [comment]
I tried to compile an old project with modern OCaml-websocket, and it failed upon trying `open Websocket`. I reckon the API has changed in the meantime.  Anyway, with `open Websocket` and a few extra tweaks it works now!

**Comment by vbmithr** [comment]
Strange because now, you should open Websocket_lwt, not Websocket.

**Comment by darioteixeira** [comment]
Sorry, I meant `open Websocket_lwt`, of course!
