### ISSUE TITLE
Default Rng generator

### ISSUE THREAD

**Issue by zoggy** [vbmithr/ocaml-websocket#46]
Hello,

`Websocket_lwt.establish_standard_server` now takes a `~g` parameter. Would it be possible to make it optional and use `!Nocrypto.Rng.generator` as in various places in `tests/*ml` ? This would prevent breaking API...

**Comment by vbmithr** [comment]
On 31/03/2016 00:02, Zoggy wrote:
> |Websocket_lwt.establish_standard_server| now takes a |~g| parameter.
> Would it be possible to make it optional and use
> |!Nocrypto.Rng.generator| as in various places in |tests/*ml| ? This
> would prevent breaking API...
> 

Ok, I did this in order to make obvious to the user that he has to
provide a seeded generator. I could indeed make these optional. I think
you might be right on this.

Vincent

**Comment by zoggy** [comment]
Thanks!
