### ISSUE TITLE
Websocket_cohttp_lwt not installed by opam?

### ISSUE THREAD

**Issue by tizoc** [vbmithr/ocaml-websocket#63]
I see that there is no mention of that module in `build.ml`.

Is it not included on purpose because it is not working yet?

**Comment by vbmithr** [comment]
Probably, I never used this code personally, I know that someone coded it but never tried it and did not remember if it was or not included.

**Comment by tizoc** [comment]
Fair enough. I'm just trying to figure out how I would implement this myself from outside of the library, but I noticed is that I would need some`Websocket.IO` functionality which isn't exposed either. Even if so, I'm using Opium, and it doesn't expose the connection handle for the http request which means that even if `Websocket_cohttp_lwt` was exposed I would not be able to use it anyway.

**Comment by vbmithr** [comment]
Fixed via f73943286825c4df979ef113e728c9d8bb1ece4b.
`#require "websocket-lwt.cohttp";;`
