### ISSUE TITLE
Don't install a module named Rng

### ISSUE THREAD

**Issue by copy** [vbmithr/ocaml-websocket#69]
Currently this library installs a module named `Rng`, which can cause problems with other libraries that might choose this name.

```
utop [1]: #require "websocket.async";;
utop [2]: Rng.cryptokit;;
- : Cryptokit.Random.rng -> Rng.t = <fun>
```

**Comment by vbmithr** [comment]
Fixed via f73943286825c4df979ef113e728c9d8bb1ece4b.
