### ISSUE TITLE
cohttp.1.0.0 support

### ISSUE THREAD

**Issue by Freyr666** [vbmithr/ocaml-websocket#96]
It seems that there are a few changes in cohttp.1.0.0 compared to 0.99 (mostly Cohttp_lwt_body deprecation in favor of Cohttp_lwt.Body).

**Comment by rgrinberg** [comment]
Note that Cohttp_lwt.Body is present in 0.99. So you don't necessarily have to bump your constraints to make your code 1.0 compatible.

**Comment by vbmithr** [comment]
Fixed.
