### ISSUE TITLE
How do I respend to client with subprotocol (Sec-WebSocket-Protocol).

### ISSUE THREAD

**Issue by kkazuo** [vbmithr/ocaml-websocket#98]
Websocket_async.client can send extra_headers, but server can not respond with subprotocol.

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers
> The client may close the connection if it doesn't get the subprotocol it wants.

I'm hit this issue and I'd like to respond to client with subprotocol header.

Thanks

**Comment by vbmithr** [comment]
Thanks for fixing :)
